#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-configparser
Version  : 3.7.3
Release  : 43
URL      : https://files.pythonhosted.org/packages/4a/4d/5d4c07cd28476ecad84ea5ad43961e50b6fd74cd24b9b81113650b4de6ee/configparser-3.7.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/4a/4d/5d4c07cd28476ecad84ea5ad43961e50b6fd74cd24b9b81113650b4de6ee/configparser-3.7.3.tar.gz
Summary  : Updated configparser from Python 3.7 for Python 2.6+.
Group    : Development/Tools
License  : MIT
Requires: deprecated-configparser-license = %{version}-%{release}
Requires: deprecated-configparser-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools-legacypython
BuildRequires : tox
BuildRequires : virtualenv

%description
.. image:: https://img.shields.io/pypi/v/configparser.svg
:target: https://pypi.org/project/configparser

%package legacypython
Summary: legacypython components for the deprecated-configparser package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-configparser package.


%package license
Summary: license components for the deprecated-configparser package.
Group: Default

%description license
license components for the deprecated-configparser package.


%package python
Summary: python components for the deprecated-configparser package.
Group: Default

%description python
python components for the deprecated-configparser package.


%prep
%setup -q -n configparser-3.7.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554309292
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-configparser
cp LICENSE %{buildroot}/usr/share/package-licenses/deprecated-configparser/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-configparser/LICENSE

%files python
%defattr(-,root,root,-)
